### ISSUE TITLE
Message: no such element: Unable to locate element

### ISSUE THREAD

**Issue by fabsta** [lg08/kindle_notion_syncer#7]
I just tried running
`python3 python3 kindle_notion_syncer.py` 
in the heroku bash and got the following error

`Amazon.com
Traceback (most recent call last):
  File "/app/kindle_notion_syncer.py", line 8, in <module>
    book_highlights = get_highlights(email, password)
  File "/app/kindle_scraper.py", line 32, in get_highlights
    email_input = driver.find_element(By.XPATH, '//*[@id="ap_email"]')
  File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 857, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/app/.heroku/python/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="ap_email"]"}
  (Session info: headless chrome=108.0.5359.124)
Stacktrace:
`

Any ideas? Maybe Amazons API has changed?

**Comment by MohamedEmary** [comment]
getting the same error, any updates?

**Comment by abdullah332** [comment]
![Screenshot 2023-03-11 021924](https://user-images.githubusercontent.com/26314925/224430724-b70ed1e0-be7c-448a-92b4-84e6e3214889.png)

**Comment by gyos23** [comment]
These are the issues for anyone that can code!

<img width="883" alt="CleanShot 2023-09-11 at 12 22 43@2x" src="https://github.com/lg08/kindle_notion_syncer/assets/12598842/c41c4d03-8e11-4e20-bb08-0db0bf8a7af1">

<img width="585" alt="CleanShot 2023-09-11 at 12 21 36@2x" src="https://github.com/lg08/kindle_notion_syncer/assets/12598842/1b39421f-2a0b-4c06-946d-38927d70c9f8">
