### ISSUE TITLE
Errors when running

### ISSUE THREAD

**Issue by dvdmon** [lg08/kindle_notion_syncer#9]
I'm running this manually with BASH inside on Heroku and getting the following (I initially had 2-factor auth on my Amazon account but removed that, triple checked my username and password:

$ python3 kindle_notion_syncer.py
getting driver---------------
Amazon Sign-In
logging in...
Traceback (most recent call last):
  File "/app/kindle_notion_syncer.py", line 8, in <module>
    book_highlights = get_highlights(email, password)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/kindle_scraper.py", line 43, in get_highlights
    elem = WebDriverWait(driver, 45).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x562a107f4fe3 <unknown>
#1 0x562a10533d36 <unknown>
#2 0x562a10570c4d <unknown>
#3 0x562a10570d61 <unknown>
#4 0x562a105ac6a4 <unknown>
#5 0x562a105918ed <unknown>
#6 0x562a105aa232 <unknown>
#7 0x562a10591693 <unknown>
#8 0x562a1056403a <unknown>
#9 0x562a1056517e <unknown>
#10 0x562a107b6dbd <unknown>
#11 0x562a107bac6c <unknown>
#12 0x562a107c44b0 <unknown>
#13 0x562a107bbd63 <unknown>
#14 0x562a1078ec35 <unknown>
#15 0x562a107df138 <unknown>
#16 0x562a107df2c7 <unknown>
#17 0x562a107ed093 <unknown>
#18 0x7fa8482b1b43 <unknown>

**Comment by sjhsz** [comment]
Came across the same issue. Double checked every step. Uncertain how to troubleshoot. Grateful if there's a resolution to this. Very excited for this tool!

**Comment by richgourmet** [comment]
+1 also ran into the same issue and received the same messages

**Comment by Hooning** [comment]
I also had the same problem. Unfortunately, I had to remove all things I just did by following your tutorial.
But overall great work :)

**Comment by gyos23** [comment]
These are the issues for anyone that can code!

<img width="883" alt="CleanShot 2023-09-11 at 12 22 43@2x" src="https://github.com/lg08/kindle_notion_syncer/assets/12598842/c41c4d03-8e11-4e20-bb08-0db0bf8a7af1">

<img width="585" alt="CleanShot 2023-09-11 at 12 21 36@2x" src="https://github.com/lg08/kindle_notion_syncer/assets/12598842/1b39421f-2a0b-4c06-946d-38927d70c9f8">

**Comment by olivierguy36** [comment]
+1 no success here. Anyone was help to fix it ?
